const orders = [
  {userId: 1, isCart: true},
  {userId: 2, isCart: true},
  {userId: 2, isCart: false},
  {userId: 2, isCart: false},
  {userId: 3, isCart: true},
  {userId: 3, isCart: false},
  {userId: 3, isCart: false},
  {userId: 3, isCart: false},
  {userId: 3, isCart: false},
  {userId: 3, isCart: false},
  {userId: 4, isCart: true},
  {userId: 4, isCart: false},
  {userId: 5, isCart: false},
  {userId: 5, isCart: true},
  {userId: 6, isCart: true},
  {userId: 6, isCart: false},
  {userId: 6, isCart: false},
  {userId: 6, isCart: false},
  {userId: 7, isCart: true},
  {userId: 7, isCart: false},
  {userId: 8, isCart: true},
  {userId: 8, isCart: false},
  {userId: 9, isCart: true},
  {userId: 9, isCart: false},
  {userId: 9, isCart: false},
  {userId: 9, isCart: false},
  {userId: 9, isCart: false},
  {userId: 10, isCart: true},
  {userId: 10, isCart: false},
  {userId: 10, isCart: false}
]

module.exports = orders
